- change/@nova-react-38c687a3-505a-4ecc-bf08-660ac12cbdf7.json
- packages/nova-react/README.md
- packages/nova-react/package.json
- packages/nova-react/src/graphql/taggedNode.ts
`require` is not legal in ES modules. We can only use the `import` keyword
1. Replacing the "require" with a static import:
```js
/**
* Imports graphql-js-tag from a peer dependency.
* 
* @graphitation/graphql-js-tag is expected to be provided by the consumer using this library.
* Failure to do so will result in a TypeScript compilation or a bundling error - there is no
* need to incur runtime costs to run checks for this library as a dependency.
*/
import { graphql as graphqlJsTag } from "@graphitation/graphql-js-tag";
```
2. Moves the `@graphitation/graphql-js-tag` as peerDep + devDep
3. Adds a little note in README.md about the pre-req
4. Removed the use of "invariant" to do checks for the dep
> .mjs fix for taggedNode

- change/@nova-react-8525508c-a4bb-4dad-90d1-6cb5f5147600.json
- change/@nova-react-test-utils-8506f5a5-66a2-4800-9b23-2ddf8fbf0cc1.json
- change/@nova-types-d6a1e6e5-1188-47c6-82ed-17383f77a62d.json
- packages/nova-react-test-utils/package.json
- packages/nova-react/package.json
- packages/nova-types/package.json
Allows webpack to safely remove any unused exports by hinting that our modules do not implicitly perform any work solely by virtue of importing them.
> Add side effects false to all packages

- change/@nova-types-7713dafb-2389-49fc-b04c-98e418485981.json
- packages/nova-types/src/nova-commanding-centralized.interface.ts
We have one more entity type that needs to be added to get to parity support in office-start for message extensions.
> Adding entity type for M365 message extensions.

- change/@nova-types-feb1beb5-7855-4232-878b-68e26e113dca.json
- packages/nova-types/src/nova-commanding-centralized.interface.ts
Meet app is new experience which we going to show in left of Teams App.
In this PR, adding Meet app in supported Entity type
> Meet app: Adding Meet app in supported entity list

- change/@nova-react-cfc47f2c-d233-4792-8864-39974ea6995a.json
- change/@nova-types-659bc505-b84d-40d3-a7a0-8f83c398423e.json
- packages/nova-react/src/eventing/nova-eventing-provider.test.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
- packages/nova-react/src/eventing/react-event-source-mapper.test.ts
- packages/nova-react/src/eventing/react-event-source-mapper.ts
- packages/nova-react/src/index.ts
- packages/nova-types/src/index.ts
- packages/nova-types/src/nova-eventing.interface.ts
Nova Eventing is designed to replace Nova Centralized Commanding as the preferred method of communication from Nova UI components.
Unlike commanding, which couples the UI components to the knowledge of who they are communicating with, eventing allows the components to define their own event shapes, which handlers in the higher business logic layers can interpret and respond to as needed.
> Nova Eventing

- change/@nova-types-2034fe2e-819c-4040-bd83-260d3c18e008.json
- packages/nova-types/src/index.ts
Exports were missing for the new commanding types, fixing that.
> Add exports for commanding types

- change/@nova-react-41a33ffb-b7b9-480a-9302-6346b4128802.json
- packages/nova-react/src/eventing/nova-eventing-provider.test.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
Looking at scenarios in Teams, the host applications may need to change the functions they are using to bubble events with.
This change encapsulates the current callback functions within refs, and prevents cascading rerenders to the children of the NovaEventing provider should these functions change.
> Stabilize Eventing across function changes

- change/@nova-react-test-utils-a107f215-b954-4488-8be4-52db5d40134e.json
- packages/nova-react-test-utils/src/nova-mock-environment.tsx
- packages/nova-react-test-utils/src/test-utils.test.tsx
- packages/nova-react-test-utils/src/test-utils.tsx
As commanding is obsolete, for completeness it would be nice to mock nova eventing on the test environment. This PR adds the mentioned basic eventing mock to allow consumers of the package to make assertions on it.
> feat(nova-react-test-utils): add eventing mock to nova test environment

- change/@nova-react-30a04f5f-7bd3-4681-8961-7b6e6de5a434.json
- change/@nova-types-1d16fa1d-4ada-4265-ab2f-9ec90486cfb1.json
- packages/nova-react/src/eventing/react-event-source-mapper.test.ts
- packages/nova-react/src/eventing/react-event-source-mapper.ts
- packages/nova-types/src/nova-eventing.interface.ts
React SyntheticEvent timestamps are based on the DOM event timeStamps that are derived as 'time since document load'. (https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp).
The timeStamp field on the Nova Source object is expected to use the Javascript Epoch time format (milliseconds since Jan 1 1970).
This change uses the underlying event data attached to the React SyntheticEvent to convert the UIEvent timeStamp into standard Epoch format, and falls back to Date.now() if the data is not available.
> Fix Source timeStamp to consistently use Epoch time

- change/@nova-react-test-utils-4384258e-c0ad-46fc-9e2c-9451950fc9b9.json
- packages/nova-react-test-utils/src/test-utils.test.tsx
- packages/nova-react-test-utils/src/test-utils.tsx
Fixes #8. It's a breaking change but a needed one. When bumping version in TMP we will have to pass the schema manually
> breaking(nova-react-test-utils): remove dependency on Teams schema

- .eslintrc.json
- .github/workflows/pr.yml
- change/@nova-react-267298f4-e478-4e2d-b528-3b6f920f2414.json
- change/@nova-react-test-utils-0afe95dc-e40e-4326-9c01-cd70e9721904.json
- change/@nova-types-77a00663-35e1-4c3b-8940-a10acd7f557b.json
- packages/nova-react-test-utils/package.json
- packages/nova-react-test-utils/src/nova-mock-environment.tsx
- packages/nova-react-test-utils/src/test-utils.test.tsx
- packages/nova-react-test-utils/src/test-utils.tsx
- packages/nova-react/src/commanding/nova-centralized-commanding-provider.test.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.test.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
- packages/nova-react/src/eventing/react-event-source-mapper.test.ts
- packages/nova-react/src/eventing/react-event-source-mapper.ts
- packages/nova-react/src/graphql/hooks.test.tsx
- packages/nova-react/src/graphql/hooks.ts
- packages/nova-react/src/graphql/nova-graphql-provider.test.tsx
- packages/nova-types/src/nova-commanding.interface.ts
- packages/nova-types/src/nova-graphql.interface.ts
- scripts/package.json
- tsconfig.json
- yarn.lock
In scope of this PR we make set of our eslint/tsconfig rules a little stricter:
* we add recommended config from `@typescript-eslint` and fix major issues
* we force using type import where applicable ([importsNotUsedAsValues](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues)) - that is useful particularly for modern build tools (when [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules) is also set)  and from dev perspective allows to easier understand what is just needed for type and what during runtime
* some more reasonable defaults in tsconfig ([forceConsistentCasingInFileNames](https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames), [noUnusedLocals](https://www.typescriptlang.org/tsconfig#noUnusedLocals), …
> refactor: use type imports and recommended lint rules, bump dependencies

- change/@nova-react-e930d68b-92b8-4323-90d9-f0669c54ae0e.json
- change/@nova-react-test-utils-c1341138-0c64-4d5d-9bf0-0ac547a4bc9e.json
- packages/nova-react-test-utils/package.json
- packages/nova-react/package.json
- yarn.lock
We are using pretty old version of react in nova-facade. Seems though that our main consumers (TMP, 1JS, App Bar) are all already at version 17. Let's bump.
Please let me know if there are any reasons we shouldn't but at least in 1JS we will be able to remove some resolutions thanks to that :)
> deps(nova-react, nova-react-test-utils): bump React to 17

- .eslintrc.json
- package.json
- scripts/config/jest.config.js
- scripts/just.config.ts
- scripts/package.json
- yarn.lock
When working on #72 I noticed some dependencies are pretty old and it caused issues with for example `satisfies` syntax in typescript. In scope of this PR we bump root repo dependencies and apply necessary migrations.
> deps: bump root dependencies

- change/@nova-react-2f32fdc6-3d91-4ef6-a1cc-c230cf674e55.json
- change/@nova-react-test-utils-f39ce6bd-4d0d-41eb-a9ed-493bc7576cf5.json
- change/@nova-types-fac25c58-df02-45ee-9ba9-8463b9694634.json
- packages/nova-react-test-utils/package.json
- packages/nova-react/package.json
- packages/nova-types/package.json
When building with strict mode with Typescript 5.0 using [`resolvePackageJsonExports`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#resolvepackagejsonexports), Typescript will ignore the root `types` field and look for `types` in the `exports` entry being imported. If it's not present, then no type information is imported, and it will throw if `strict` mode is enabled.
The simple fix here is to mirror the root `types` field in `exports["."].types`.
Additionally, I added links to this repository in the `package.json`, as I had to ask around to find the repository.
> Update package.json files with exports.types and repository entries

- change/@nova-react-aefe8057-bbfd-45da-97e9-8fe424c4acaf.json
- change/@nova-types-127764de-3d1d-4990-b7db-862910f13cba.json
- packages/nova-react/src/graphql/hooks.test.tsx
- packages/nova-react/src/graphql/hooks.ts
- packages/nova-react/src/graphql/types.ts
- packages/nova-types/src/nova-graphql.interface.ts
Follow up from PR in duct-tape: https://github.com/microsoft/graphitation/pull/297
This PR updates hooks to support the passing of context.
> Update nova hooks to support context

- change/@nova-react-b4586a9b-4aa7-4cfa-8a5c-81fe8d19a33f.json
- packages/nova-react/src/graphql/hooks.ts
Small fix to make context an optional parameter in useSubscription hook
> Make context optional in use subscription

- change/@nova-react-2a92f71d-e096-4da8-afb5-d02dd26f4bc9.json
- packages/nova-react/src/eventing/nova-eventing-provider.test.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
We've discovered a need to have two versions of eventing at once during component unmounts. Useeffect cleanup functions need to use the old version of eventing to get the old context to ensure proper routing of events. This change will allow hosts to maintain two eventing references, with the unmount eventing switching out later to keep the reference to the old execution context before unmount.
This change adds a useNovaUnmountEventing hook in the nova eventing provider. It is supplied by a new `unmountEventing` property. If the new property is not supplied, the new hook will use the existing eventing reference, to maintain backwards compatibility with nova hosts which do not need this functionality.
> Add unmountEventing through the NovaEventingProvider

- change/@nova-react-901b72d6-78fa-4a51-9e04-ccf26c8e45bf.json
- packages/nova-react/package.json
- packages/nova-react/src/commanding/nova-centralized-commanding-provider.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
- packages/nova-react/src/graphql/nova-graphql-provider.tsx
When trying to use `@nova/react` with React 18 the typings for the providers are not correct as `children` now has to be explicitly defined on the Props type.
This adds the `children` prop to all the providers but keeps us on React 17 for now as that is what most of the internal projects still use. The fix should however allow React 18 users to use `@nova/react` without any errors.
> Allow React 18 to a peerDependency and fix Provider Prop types

- change/@nova-react-8a6bad44-a7eb-4078-8e64-97d0eaeedc62.json
- packages/nova-react/src/graphql/hooks.test.tsx
- packages/nova-react/src/graphql/types.ts
Relay 16 generates the following fragment type
```ts
export type JobTitleFragment$key = {
readonly " $data"?: JobTitleFragment$data;
readonly " $fragmentSpreads": FragmentRefs<"JobTitleFragment">;
};
```
Our hooks currently only support the older `" $fragmentRefs"` format that looks as follows.
```ts
export type JobTitleFragment$key = {
readonly " $data"?: JobTitleFragment$data;
readonly " $fragmentRefs": FragmentRefs<"JobTitleFragment">;
};
```
This means that when generating code with newer versions of the relay-compiler we can not use those generated fragments with `useFragment` and will get the following error.
```
Argument of type 'JobTitleFragment$key' is not assignable to parameter of type 'Readonly<{ " $data"?: unknown; " $fragmentRefs": unknown; }>'.
Property '" $fragmentRefs"' …
```
> Add  support for Relay 13+ generated code by adding $fragmentSpreads support

- change/@nova-react-test-utils-6eb41ac7-0d52-4bf2-a2d3-25a22cef2bc2.json
- packages/nova-react-test-utils/README.md
- packages/nova-react-test-utils/src/storybook-nova-decorator.tsx
- packages/nova-react-test-utils/src/test-utils.tsx
In Jana we want to rely on `@graphitation/apollo-react-relay-duct-tape` with watch fragments to be able to use `useReftchable/PaginationFragment` hooks. However, to get them to work one needs a specific cache config for apollo client, even for the mock one. In this PR we add an option to pass that, matching interface of apollo-mock-client itself
> feat(react-test-utils): add possibility to configure cache of mock client

- change/@nova-graphql-compiler-e72520b4-ef21-4e7e-b424-2ea556b89389.json
- change/@nova-react-test-utils-0110d9fc-466e-4726-90dc-ee51b696c71e.json
- packages/nova-graphql-compiler/package.json
- packages/nova-graphql-compiler/src/cli.test.js
- packages/nova-react-test-utils/package.json
- yarn.lock
There are two issues that this PR is trying to fix:
* running tests for compiler fails on windows because `spawnSync` is not cross platform
* repoes which depend on @nova/react-test-utils have to force version of duct tape as the current range is not deduplicatble with 1.x.
We fix both
> Bump duct tape version for package deduplication and make compiler test work on windows

- change/@nova-react-c10c9e36-4cda-4e41-bc32-85c8d2031bdb.json
- packages/nova-react/package.json
- packages/nova-react/src/graphql/hooks.test.tsx
- packages/nova-react/src/graphql/hooks.ts
- packages/nova-react/src/graphql/types.ts
- yarn.lock
Relay allows for fragment references  to be `null` or `undefined`. Our typings have been stricter where they do not allow `null` or `undefined`. 
This causes us to miss out on things like `@skip` and `@include`.
This PR adds the ability to pass `null` or `undefined` as the fragment reference to `useFragment` `usePaginationFragment` or `useRefetchableFragment`.
> Allow fragment refs to be null or undefined

- change/@nova-react-296f014e-8381-4885-8e4e-fda27caec88f.json
- packages/nova-react/src/graphql/types.ts
`RefetchOptions` type has an incorrect signature and causes linting issues on `onComplete` function usage.
> Fix RefetchOptions onComplete function type

- change/@nova-react-test-utils-08977333-6b8c-48b3-9634-fcb346089ad7.json
- packages/nova-react-test-utils/package.json
- packages/nova-react-test-utils/src/apollo/test-utils.tsx
- packages/nova-react-test-utils/src/relay/test-utils.tsx
- packages/nova-react-test-utils/src/shared/nova-mock-environment.tsx
- yarn.lock
When trying to use new version of the decorator in 1JS there are a couple of issues related to dependencies not being declared. Similarly when @kerrynf tried to integrate it in client-web she also had a couple of missing dependencies problems. Let's make sure to correctly declare the ones that are not optional and unify a bit how we declare versions compatible
> feat(react-test-utils): fix some issues with dependenies

- change/@nova-examples-4250c57c-5ffc-4445-a314-deecf9b17553.json
- packages/examples/jest.config.ts
- packages/examples/src/testing-utils/executePlayFunction.ts
- packages/examples/tsconfig.jest.json
- scripts/config/jest.config.ts
- scripts/config/jest.setup.ts
- scripts/config/jest.setupAfterEnv.ts
- scripts/just.config.ts
Following up on a [comment](https://github.com/microsoft/nova-facade/pull/109#discussion_r1763744663) from #109 we improved handling of having package specific configurations:
* we change just scripts to prioritize using package local Jest config if it exists
* we move logic that handles transforms for graphql file and relay compiler generated artifacts to jest config in `examples` package
* we remove a hack we added in `jest.setupAfterEnv` file by using `/pure` imports from RTL
> fix(examples): improve handling of local jest config and remove RTL clean hack

- change/@nova-react-test-utils-c3c25173-e0c9-493b-b4f3-682a4a4e0f42.json
- packages/nova-react-test-utils/src/shared/types.d-test.ts
- packages/nova-react-test-utils/src/shared/types.ts
In #114 we added improved types but turns out we missed one case for components which have optional props only. Let's fix this and add a type test.
> fix(nova-react-test-utils): fix StoryObjWithoutFragmentRefs type

- change/@nova-examples-c7b407c4-0f7d-4998-9e44-6060439c77d4.json
- change/@nova-react-test-utils-2c56a133-6ab5-4005-b9c8-e62c10473986.json
- packages/examples/src/apollo/Feedback/Feedback.test.tsx
- packages/examples/src/apollo/Feedback/Feedback.tsx
- packages/examples/src/apollo/Feedback/FeedbackContainer.test.tsx
- packages/examples/src/events/events.ts
- packages/examples/src/events/helpers.ts
- packages/examples/src/relay/Feedback/Feedback.test.tsx
- packages/examples/src/relay/Feedback/Feedback.tsx
- packages/examples/src/relay/Feedback/FeedbackContainer.test.tsx
- packages/examples/src/relay/pure-relay/Feedback.test.tsx
- packages/examples/src/relay/pure-relay/Feedback.tsx
- packages/nova-react-test-utils/src/shared/storybook-nova-decorator-shared.tsx
While testing the new decorator in 1JS we discovered that when the `rerender` from React Testing Library is used, fragment based components, powered by decorator get remounted instead of rerendered. The reason was lack of stable identity for the `Renderer` function in shared decorator. In scope of this PR we refactor it to proper component, which gets us the stable identity and no remounts.
The important change is in `nova-react-test-utils`, rest are tests for the scenario which would fail before this change
> fix(nova-react-test-utils): prevent component unmount when using decorator with RTL rerender

- change/@nova-examples-b005d778-782a-4b62-8b10-35b4f3182904.json
- change/@nova-react-test-utils-35868734-fda7-4b84-9bee-73b9f577ce70.json
- packages/examples/package.json
- packages/examples/src/relay/Feedback/Feedback.stories.tsx
- packages/examples/src/relay/pure-relay/Feedback.stories.tsx
- packages/nova-react-test-utils/README.md
- packages/nova-react-test-utils/src/relay/storybook-nova-decorator-relay.tsx
- yarn.lock
As we discovered when integrating new decorator in 1JS, there is a problem with passing relay environment config to the decorator. The issue is that when one used as in docs `getNovaDecorator(schema, { store: createStores() })` that would cause a store to be shared between multiple stories as `createStore` function was executed once for the whole decorator. This means that we cannot just pass relay env options directly instead we change the code to pass function that gets the options.
Tested using storybook and verifying each has unique data in store and results of resolvers don't not slip over. Theoretically it is a breaking change but as the option was not yet widely used, we mark it as minor.
Special thanks to @jakobkhansen for reporting and creating repro of the issue in …
> fix(nova-react-test-utils): fix issue with store being shared between stories

- change/@nova-react-f0f39448-a25c-42e0-a43f-ffbc21cef7de.json
- change/@nova-react-test-utils-adf668c1-9898-44c0-928f-a9e9ad6f6b79.json
- packages/nova-react-test-utils/src/apollo/test-utils.tsx
- packages/nova-react-test-utils/src/apollo/utils.test.tsx
- packages/nova-react-test-utils/src/shared/nova-mock-environment.tsx
- packages/nova-react/src/commanding/nova-centralized-commanding-provider.test.tsx
- packages/nova-react/src/commanding/nova-centralized-commanding-provider.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.test.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
- packages/nova-react/src/graphql/hooks.test.tsx
- packages/nova-react/src/graphql/hooks.ts
- packages/nova-react/src/graphql/nova-graphql-provider.test.tsx
- packages/nova-react/src/graphql/nova-graphql-provider.tsx
- scripts/config/jest.config.ts
- tsconfig.json
A lot of packages in 1JS need to update their tsconfig when integrating new test utils, due to default imports on `React` and `invariant`. Instead of forcing the change, we can adjust imports inside the package and remove the need of setting `esModuleInterop`. As verification, we removed that from the tsconfig in the repo itself
> fix(nova-react-test-utils): replace default imports with * imports

- change/@nova-react-7777c2ef-6eb5-4013-bbf2-3d51bb071261.json
- packages/nova-react/src/commanding/nova-centralized-commanding-provider.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
- packages/nova-react/src/graphql/hooks.ts
- packages/nova-react/src/graphql/nova-graphql-provider.tsx
- scripts/config/jest.config.ts
In #120 we replace all `import React as "react"` and all `import invariant from "invariant"` to be * imports to mitigate issues due to failures in 1JS when seeing `import React as "react"` even in ES modules. However, there were no complaints about invariant and we did change anyway. Turns out that wasn't a good idea because then when running jest in 1JS (or anywhere else were we use /lib files from facade) we get `Error: Uncaught [TypeError: invariant is not a function]` as `invariant` really has a default export which is a single function and then 
is missing .default to work :(
So to at least avoid having to set `esModuleInterop` outside of Jest, we bring back the default import for invariant but set `esModuleInterop` for tests only (which is also set in 1JS and TMP in default jest …
> fix(nova/react): bring back default import for invariant

- change/@nova-react-198378aa-bbb8-4a24-8ce3-2d0718002e1e.json
- packages/nova-react/README.md
- packages/nova-react/src/eventing/nova-eventing-provider.test.tsx
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
When there are multiple interceptors, only the last one is called.
The interceptor is reading 'internal' which always refers to the novaEventing set by eventing provider. When setting the context in the interceptor, the same internal is used instead of creating a new one. The internal in the eventing should point to eventing/unmountEventing created by the interceptor and not the root nova eventing.
> fix(nova/react): fix eventing for multiple nova event interceptors

- change/@nova-react-d004a70b-8f43-4bdf-8ec0-2e62cb34ed05.json
- packages/nova-react/src/eventing/nova-eventing-provider.tsx
The function creating internal object contains hooks, so it should not be called inside useMemo.
> fix: follow rules of hooks

- .azure-devops/nova-facade-release.yml
Do not use PAT token for our service account and use persistCredentials instead.
> feat(pipelines): set persistCredentials for beachball

- change/@nova-examples-47747cb9-5ddf-433f-b1b3-1a981b7afca2.json
- change/@nova-react-test-utils-14e2b035-68e8-4194-a665-d6471a4c4986.json
- packages/examples/data/schema.graphql
- packages/examples/src/relay/pure-relay/ViewDataOnly.stories.ts
- packages/examples/src/relay/pure-relay/ViewDataOnly.test.tsx
- packages/examples/src/relay/pure-relay/ViewDataOnly.tsx
- packages/nova-react-test-utils/src/relay/nova-relay-graphql.ts
Multiple users in 1JS complained that it is hard to figure out why mock data is not being generated in certain cases and specified resolvers are not even executed. Turns out it was because in Relay client extensions only queries don't even reach "server" resolvers so there is nothing to generate, check facebook/relay#4927.
To make it less confusing for our devs, until we have either a fix in relay or graphitation payload generator supporting client extensions, let's throw an informative error, to let devs know what they should do.
> feat(nova/react-tets-utils): throw an error if user has client extensions only query in relay variant

- change/@nova-examples-a8a23456-2e26-4259-9c9d-78a2c0893f42.json
- change/@nova-react-test-utils-f60f28a3-271f-4091-9f3b-966b95b74ad2.json
- packages/examples/package.json
- packages/nova-react-test-utils/src/shared/storybook-nova-decorator-shared.tsx
- scripts/package.json
- yarn.lock
1JS bumped to TS 5.8 and they needed to create a patch to make testing utilities compatible with the new version of TypeScript. In this PR we bump the TS in the repo and push patched changes
> fix: bump TS and fix compatibility in 1JS

- change/@nova-examples-c0e28e10-db82-44dc-bd30-79896810d3f2.json
- change/@nova-react-test-utils-1b789a4f-9d17-431c-a10e-002e53f6a681.json
- packages/examples/src/relay/Feedback/Feedback.stories.tsx
- packages/examples/src/relay/Feedback/Feedback.test.error.tsx
- packages/examples/src/relay/pure-relay/extensions/ViewDataOnly.stories.ts
- packages/examples/vitest.config.ts
- packages/examples/vitest.plugins.ts
- packages/nova-react-test-utils/README.md
- packages/nova-react-test-utils/src/relay/nova-relay-graphql.ts
Before: 
After:
Change done based on feedback from some confused 1JS devs. Added unit test which verifies this error flow
> fix(nova-react-test-utils): throw an informative error when artifacts loader is missing

- change/@nova-react-8f0ecf0d-0fe8-4af9-a35a-48acbbd52bf3.json
- packages/nova-react/src/graphql/hooks.test.tsx
- packages/nova-react/src/graphql/hooks.ts
- packages/nova-react/src/graphql/types.ts
Relay's `useFragment` supports plural typings when `@relay(plural: true)` directive is set on the fragment. Typings in Nova currently do not allow this. See #147.
The PR adds two new signatures to `useFragment` hook definition, one for non-nullable array of refs and the other one for a nullable array. Nova already had `ArrayKeyType` and `ArrayKeyTypeData` utility types defined, they just were not used anywhere.
Only `useFragment` is updated since Relay does not support plural fragments for any other fragment hooks (e.g., `useRefetchableFragment`).
> Add plural typings for usefragment

- change/@nova-examples-5cb6aef4-c7d5-4af4-8706-3aea7326df71.json
- change/@nova-react-test-utils-61f6d56b-3b82-42d2-b4b8-3c20edd76731.json
- packages/examples/src/relay/pure-relay/extensions/ViewDataOnly.stories.ts
- packages/nova-react-test-utils/src/relay/nova-relay-graphql.ts
In 1JS we have multiple instance of folks having nested view data queries and then the decorator blows up as it wasn't an expected scenario. One can still make it work by filling the store for that specific piece of view data in some other query but thrown error makes the DX pretty and requires import change to use relay directly. To make DX better but still give feedback to user we rely on console warnings instead,
Also with facebook/relay#4999 by @jakobkhansen we soon will be able to support client extensions properly
> fix(nova-react-test-utils): relax error on view data only queries

- change/@nova-schema-dba179e9-3aaa-4ac8-82ba-d45c8cd2bd07.json
- packages/nova-schema/README.md
- packages/nova-schema/index.graphql
- packages/nova-schema/package.json
Nova defines extra pieces of SDL to allow high-value components to provide extra metadata as a part of their GraphQL schema. This new package will be used to host these SDL declarations, and can be used both for documentation purposes and for GraphQL tooling.
> Add @nova/schema package
